### PR TITLE
Added first view with data fetched from Azure Db

### PR DESCRIPTION
**Pull request by PoojaJagaragallu**

### CODE REVIEW

**Review by shaikhwajeed — CHANGES_REQUESTED** [review]
Please remove commented code.

**Comment by PoojaJagaragallu** [comment]
Please don't give any comments without knowing the actual use of the commented code.

**Comment by shaikhwajeed** [comment]
This is not an expected behavior.

**Comment by shaikhwajeed** [comment]
Please don't close the pull request without closign all the issues.

**Comment by shaikhwajeed** [comment]
It's no cool.
=
You were right here while this was being done!!

**Review by shaikhwajeed — APPROVED** [review]

**Pull request merged**
